name: Publish NuGet Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # 手动触发

jobs:
  build-and-pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build projects
        run: dotnet build --no-restore --configuration Release -p:Version=${GITHUB_REF_NAME#v}

      - name: Clean nupkg folder
        run: rm -rf ./nupkg && mkdir ./nupkg

      - name: Pack Jasper.Allinpay.Core
        run: dotnet pack Jasper.Allinpay.Core/Jasper.Allinpay.Core.csproj --no-build --output nupkg -p:Version=${GITHUB_REF_NAME#v} -p:Configuration=Release

      - name: Pack Jasper.Allinpay.AspNetCore
        run: dotnet pack Jasper.Allinpay.AspNetCore/Jasper.Allinpay.AspNetCore.csproj --no-build --output nupkg -p:Version=${GITHUB_REF_NAME#v} -p:Configuration=Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: ./nupkg/*.nupkg

      - name: Push packages to NuGet.org
        run: |
          for f in ./nupkg/*.nupkg; do
            dotnet nuget push "$f" \
              --source https://api.nuget.org/v3/index.json \
              --api-key ${{ secrets.NUGET_API_KEY }} \
              --skip-duplicate
          done
